server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/ecom
      database: ecom

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.connection: INFO
